// Global styles
import '../styles/globals.scss';

export const metadata = {
  title: 'CMS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
