// React
// import React, { useEffect, useState } from 'react';

// Components
import { Layout } from '@/components';

// Global styles
import '../styles/globals.scss';

export const metadata = {
  title: 'CMS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Layout>
      {children}
    </Layout>
  )
}
